name: neuro-agent
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - poetry
  - pytorch
  - numpy
  - pandas
  - jupyterlab
  - pip:
      - langchain
      - sentence-transformers
      - rdflib
      - networkx
      - sympy
